In [1]:
import numpy as np

# Q1

In [2]:
a1=np.random.randint(low=1,high=5,size=5)
print(a1)
a2=np.random.randint(low=1,high=5,size=5)
print(a2)
filter=a2>a1
print("greater elements comapring a2 with a1 array is \n",a2[filter])
filter=a2>=a1
print("greater than are equal to elements comapring a2 with a1 array is \n",a2[filter])
filter=a2<a1
print("lesser elements comapring a2 with a1 array is \n",a2[filter])
filter=a2<=a1
print("lesser and lesser equal elements comapring a2 with a1 array is \n",a2[filter])

[2 3 2 2 2]
[4 3 4 4 3]
greater elements comapring a2 with a1 array is 
 [4 4 4 3]
greater than are equal to elements comapring a2 with a1 array is 
 [4 3 4 4 3]
lesser elements comapring a2 with a1 array is 
 []
lesser and lesser equal elements comapring a2 with a1 array is 
 [3]


# Q2

In [3]:
zeros=np.random.randint(low=0,high=1,size=10)
print("10 zeros are:\n",zeros)
ones=np.random.randint(low=1,high=2,size=10)
print("10 ones:\n",ones)
fives=np.random.randint(low=5,high=6,size=10)
print("10 fives are :\n",fives)

10 zeros are:
 [0 0 0 0 0 0 0 0 0 0]
10 ones:
 [1 1 1 1 1 1 1 1 1 1]
10 fives are :
 [5 5 5 5 5 5 5 5 5 5]


# Q3

In [4]:
a3=np.array([[2,2],[4,3]])
print("array is:\n",a3)
print("sum of all elements in an array : ",np.sum(a3))
ex=np.sum(a3,axis=1)
print("sum of first row is : ",ex[0])
print("sum of second row is : ",ex[1])
ex1=np.sum(a3,axis=0)
print("sum of first column is : ",ex1[0])
print("sum of second column is : ",ex1[1])

array is:
 [[2 2]
 [4 3]]
sum of all elements in an array :  11
sum of first row is :  4
sum of second row is :  7
sum of first column is :  6
sum of second column is :  5


# Q4

In [5]:
a4=np.array([[2,2],[2,3]])
print("array one :\n",a4)
a5=np.array([[2,2],[2,3]])
print("array two :\n",a5)
print("Adding of an arrays is :\n",np.add(a4,a5))
print("subtract of an arrays is :\n",np.subtract(a4,a5))
print("multiply of an arrays is :\n",np.multiply(a4,a5))
print("divide of an arrays is :\n",np.divide(a4,a5))

array one :
 [[2 2]
 [2 3]]
array two :
 [[2 2]
 [2 3]]
Adding of an arrays is :
 [[4 4]
 [4 6]]
subtract of an arrays is :
 [[0 0]
 [0 0]]
multiply of an arrays is :
 [[4 4]
 [4 9]]
divide of an arrays is :
 [[1. 1.]
 [1. 1.]]


# Q5

In [6]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("\n\ncosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("\n\ntangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]


cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Q6

In [7]:
import numpy as np
import pandas as pd


In [8]:
d={'Name':['vani','yash','Vara','Naidu',],'USN':[121,122.,123,124,],'score':[100,35,78,45]}
label={1,2,3,4,}
df=pd.DataFrame(d,label)
print(df)

    Name    USN  score
1   vani  121.0    100
2   yash  122.0     35
3   Vara  123.0     78
4  Naidu  124.0     45


# Q7

In [11]:

print(df[['Name','score']])

    Name  score
1   vani    100
2   yash     35
3   Vara     78
4  Naidu     45


# Q8

In [10]:
d3={'Name':['vani','yash','Vara','Naidu',],'USN':[121,122,123,124,],'score':[100,35,78,45]}
d2={'Name':['sai','arindam','santhosh','boss',],'USN':[125,126,127,128,],'score':[99,39,68,65]}
d5=pd.DataFrame(d3)
d6=pd.DataFrame(d2)
print(pd.concat([d5,d6]))

       Name  USN  score
0      vani  121    100
1      yash  122     35
2      Vara  123     78
3     Naidu  124     45
0       sai  125     99
1   arindam  126     39
2  santhosh  127     68
3      boss  128     65
